version: "3.5"

services:
    backend:
        build: 
            context: .
            dockerfile: Spring.Dockerfile
        container_name: backend
        ports:
            - target: 8080
              published: 8080
        links: 
            - mongodb
    mongodb:
        image: mongo:latest
        container_name: mongodb
        ports:
            - target: 27017
              published: 27017
        volumes:
            - type: volume
              source: mongodb_vol
              target: /data/db

volumes:
    mongodb_vol: 
    