const constants = {
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  ADD_TO_BAG: "ADD_TO_BAG",
  ADD_TO_FAVORIATES: "ADD_TO_FAVORIATES",
  REMOVE_FROM_BAG: "REMOVE_FROM_BAG",
  REMOVE_FROM_FAVORIATES: "REMOVE_FROM_FAVORIATES",
  UPDATE_BAG: "UPDATE_BAG"
}

export default constants
